### Configuration file for Community Firn Model simulations

### ----------------- Processing forcing data ----------------- ###

## Directories
CFM_repo_path: /home/speersm/luna/CPOM/speersm/CommunityFirnModel/CFM_main # path to the Community Firn Model repository, should contain CFM_main folder
MAR_data_path: /home/speersm/luna/CPOM/briggsk/RCM_data/Data/MAR/AIS/27.5km # path to MAR forcing data directory stored on luna
RACMO_data_path: /home/speersm/luna/CPOM/archive/MODELS/RCM/RACMO/AIS/Feb_2026/ANT-12/ERA5/evaluation/day # path to RACMO forcing data directory stored on luna
CFM_data_path: /home/speersm/luna/CPOM/speersm/CFM_data # path to store CFM input and output data
force_data_save_path_pattern: "{CFM_data_path}/cfm_input/{rcm_name}_{borehole_lat}_{borehole_lon}_{start_year}_{end_year}.csv" # configurable forcing file naming pattern

# Period
start_year: 1979
end_year: 2024

# Borehole location - this is the location at which cfm will be run if no arguments are passed
borehole_lat: -66.403
borehole_lon: -63.376

# borehole sites - these are the locations of the boreholes for which we have firn temperature profiles to compare to - used in plotting scripts mostly
borehole_sites:
  CI-0: [-66.403, -63.376]
  CI-22: [-66.588, -63.212]
  CI-120: [-67.000, -61.486]
  WI-0: [-67.444, -64.953]
  WI-70: [-67.500, -63.336]
  J108: [-67.108, -61.287]
  J208: [-68.300, -64.149]
  J409: [-68.395, -64.713]
  # J109: [-68.395, -64.710]
  # Y208: [-67.564, -63.257]

# bounding box for larsenC area
larsenC_box:
  lat_min: -75.0
  lat_max: -63.5
  lon_min: -75.0
  lon_max: -55.0

# RCM name to use for forcing data (e.g., MAR or RACMO)
rcm_name: RACMO

## MAR Sector
sector: 1.0 # only take data from this sector in MAR files (think is ice vs non-ice)

## Mapping converting MAR columns to CFM input columns
MAR_to_CFM_column_map:
  TTZ: T2m # 2m above surface temperature
  TI1: TSKIN # surface temperature
  SU: SUBLIM # sublimation
  SHF: QH # sensible heat flux
  LHF: QL # latent heat flux
  SWD: SW_d # downward shortwave radiation
  LWD: LW_d # downward longwave radiation
  RF: RAIN # rainfall
  SF: BDOT # snowfall
  AL2: ALBEDO # surface albedo
  ME: SMELT # melt

## Mapping converting RACMO columns to CFM input columns
## Some columns are not 1-1, and should be calculated from the RACMO data
## e.g., rainfall can be calculated from total precipitation and snowfall
RACMO_to_CFM_column_map:
  tas: T2m # 2m above surface temperature
  ts: TSKIN # surface temperature
  sublgl: SUBLIM # sublimation
  hfssgl: QH # sensible heat flux
  hflsgl: QL # latent heat flux
  rsds: SW_d # downward shortwave radiation
  rlds: LW_d # downward longwave radiation
  rf: RAIN # rainfall - to be calculated as rf = pr - prsn, where pr is total precipitation and prsn is snowfall
  prsn: BDOT # snowfall
  alb: ALBEDO # surface albedo - to be calculated as alb = rsusgl / rsds, where rsusgl is upward shortwave radiation and rsds is downward shortwave radiation
  mltgl: SMELT # melt

## additional RACMO variables to read in to calculate CFM inputs
RACMO_additional_vars:
  - pr # total precipitation, used to calculate rainfall from pr - prsn
  - rsusgl # upward shortwave radiation, used to calculate albedo from rsugl / rsds

## smb to multiply by to convert RACMO to MAR units
RACMO_to_MAR_smb_factor: 86400 # RACMO outputs in kg/m2/s, MAR in kg/m2/day, so multiply by number of seconds (24 * 3600) in a day to convert
RACMO_var_to_multiply:
  - mltgl
  - sublgl
  - prsn

## temperature variables in MAR to convert to Kelvin
MAR_temp_vars:
  - TTZ
  - TI1

### ----------------- CFM Simulation ----------------- ###

## model run parameters
spin_end_year: 1989 #spin date end
runid: -9999 
rho_bottom: 910 # density at bottom boundary condition
sublim_sf: -1 #sublimation scaling factor, -1 for MERRA2 data, not sure for MAR data but think also -1, -1 for RACMO

## config for CFM_main, will be saved as json in output folder
cfm_config:
  InputFileFolder: CFMinput
  InputFileNameTemp: example_tskin.csv
  InputFileNamebdot: example_smb.csv
  InputFileNameIso: example_isotope.csv
  InputFileNamerho: example_rhos.csv
  InputFileNamemelt: example_melt.csv
  resultsFolder: CFMresults
  initfirnFile: example_firndata.csv
  initprofile: false
  input_type: dataframe
  input_type_options: [csv,dataframe]
  DFresample: 1D
  DFfile: MERRA2_CLIM_df_72.5_-38.75.pkl
  physRho: GSFC2020
  physRho_options: [HLdynamic,HLSigfus,Li2004,Li2011,Helsen2008,Arthern2010S,Arthern2010T,Li2015,Goujon2003,Barnola1991,Morris2014,KuipersMunneke2015,Crocus,Ligtenberg2011]
  MELT: true
  ReehCorrectedT: false
  FirnAir: false
  AirConfigName: AirConfig.json
  TWriteInt: 1
  TWriteStart: 1980.0
  int_type: nearest
  int_type_options: [nearest,linear]
  SeasonalTcycle: false
  SeasonalThemi: north
  coreless: true
  TAmp: 10.0
  physGrain: true
  calcGrainSize: false
  GrGrowPhysics: Arthern
  GrGrowPhysics_options: [Arthern,Katsushima]
  heatDiff: true
  conductivity: Calonne2019
  conductivity_options: [Schwander,Yen_fixed,Yen_var,Anderson,Yen_b,Sturm,VanDusen,Schwerdtfeger,Riche,Jiawen,mix,Calonne2011,Calonne2019]
  variable_srho: false
  srho_type: userinput
  srho_type_options: [userinput,param,noise]
  rhos0: 350.0
  r2s0: 1.0e-8
  AutoSpinUpTime: false
  yearSpin: 20
  H: 3000
  HbaseSpin: 2880.0
  stpsPerYear: 12.0
  D_surf: 1.0
  bdot_type: mean
  bdot_type_options: [instant,mean,stress]
  grid_outputs: true
  grid_output_res: 0.05
  isoDiff: false
  iso: D
  isoOptions: [18,D,NoDiffusion]
  spacewriteint: 1
  strain: false
  du_dx: 1e-5
  outputs: [density,depth,temperature,age,DIP,meltoutputs,grainsize]
  outputs_options: [density,depth,temperature,age,Dcon,bdot_mean,climate,compaction,grainsize,temp_Hx,isotopes,BCO,DIPc,DIP,LWC,gasses,PLWC_mem,viscosity,runoff,refrozen]
  resultsFileName: CFMresults.hdf5
  spinFileName: CFMspin.hdf5
  doublegrid: true
  nodestocombine: 30
  multnodestocombine: 12
  Dnodestocombine: 30
  Dmultnodestocombine: 12
  grid1bottom: 5.0
  grid2bottom: 10.0
  spinup_climate_type: mean
  spinup_climate_type_options: [mean,initial]
  manual_climate: false
  deepT: 255.88
  bdot_long: 0.49073
  manual_iceout: false
  iceout: 0.23
  QMorris: 110.0e3
  timesetup: exact
  timesetup_options: [exact,interp,retmip]
  liquid: bucket
  liquid_options: [percolation_bucket,bucketVV,resingledomain,prefsnowpack]
  merging: false
  merge_min: 1e-4
  LWCcorrect: false
  manualT: false
  no_densification: false
  rad_pen: false
  site_pressure: 1013.25
  output_bits: float32
  spinUpdate: true
  spinUpdateDate: 1980.0
  DIPhorizon: 100.0
  NewSpin: true
  ColeouLesaffre: false
  IrrVal: 0.02
  RhoImp: 830.0
  DownToIce: false
  ThickImp: 0.1
  Ponding: false
  DirectRunoff: 0.0
  RunoffZuoOerlemans: false
  Slope: 0.1
  SUBLIM: true
  keep_firnthickness: true
  SEB_TL_thick: 0.05
  albedo_factor: 1
  bdm_sublim: true
  iceblock: false
  iceblock_rho: 917.0
  truncate_outputs: false
  stage_zero: false
  snow_model: Yamazaki1993
  s_zero_rho: 200
  SEB: true
  RAIN: true

### ----------------- Plotting ----------------- ###
thickness_change_range: [2000, 2000.25] # Range of model time to plot for change in firn thickness (in years)

# cbar limits for spatial rcm plots
rcm_plot_cbar_limits:
  ME: [0, 3.5] # in mmweq/day
  mltgl: [0, 3.5] # in mmweq/day
  TI1: [240, 275] # in K
  ts: [240, 275] # in K
  TTZ: [245, 275]
  tas: [245, 275]
  SF: [0, 15]
  prsn: [0, 15]
  SHF: [-100, 100]
  hfssgl: [-100, 100]
  LHF: [-35, 35]
  hflsgl: [-35, 35]
  SU: [-3, 3]
  sublgl: [-3, 3]

sites_batch_1: ["CI-0", "CI-22", "CI-120", "WI-0", "WI-70"]
sites_batch_2: ["J108", "J208", "J409"]